apiVersion: v1
kind: Service
metadata:
  name: serviced86ac2e8-534e-4e74-bc24-a99e630696e8
spec:
  ports:
  - name: host
    port: 8000
    targetPort: 8000
  - name: client
    port: 444
    targetPort: 444
  selector:
    app: d86ac2e8-534e-4e74-bc24-a99e630696e8
  type: LoadBalancer
