apiVersion: v1
kind: Service
metadata:
  name: jolie-deployer
spec:
  ports:
  - name: host
    port: 8000
    targetPort: 8000
  - name: client
    port: 8080
    targetPort: 8080
  selector:
    app: jolie-deployer
  type: LoadBalancer
