# To create service after the deployment has been created: run command
#	kubectl create -f embed-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: embed-service
spec:
  ports:
  - name: host
    port: 8000
    targetPort: 8000
  - name: client
    port: 8080
    targetPort: 8080
  selector:
    app: embed
  type: LoadBalancer
