apiVersion: apps/v1
kind: Deployment
metadata:
  name: jolie-deployer
  labels:
    app: jolie-deployer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jolie-deployer
  template:
    metadata:
      labels:
        app: jolie-deployer
    spec:
      containers:
      - name: jolie-deployer
        image: joelhandig/cloud_server
        ports:
        - containerPort: 8000
